const { userSeed } = require('./user.seeder')
const { cashierData } = require('./cashier.seeder')
const { guideData } = require('./guide.seeder')
const { contentSeed } = require('./contents.seeder')
const { eventSeed } = require('./event.seeder.')
const { iterationSeed } = require('./eventIterarion.seeder.')
const { nationalitySeed } = require('./nationality.seeder')
const { orderDataSeed } = require('./orderData.seeder.')
const { pageSeed } = require('./pages.seeder')
const { purchasableSeed } = require('./purchasable.seeder')
const { subTypeSeed } = require('./purchasableSubType.seeder')
const { typeSeed } = require('./purchasableType.seeder.')

async function main() {
  await userSeed()
  await cashierData()
  await guideData()
  await nationalitySeed()
  await iterationSeed()
  await eventSeed()
  await typeSeed()
  await subTypeSeed()
  await purchasableSeed()
  await orderDataSeed()
  await pageSeed()
  await contentSeed()
}

main()
